apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  namespace: gemini-namespace 
type: Opaque
data:
  GOOGLE_ID: <enter-your-google-id> # Enter your Google ID here in base64 encoded format
  GOOGLE_SECRET: R09DU1BYLTI5TzhxUlhQZmJNX202cVcyaWpRUF9fTkVHTVk= # Enter your Google secret here in base64 encoded format
  NEXTAUTH_SECRET: QkVUVEVSX0FVVEhfU0VDUkVUPWI3NWE2NjExYjNiZGRjNzExMjU2NmNkMjU0MGU2N2ZmNGIyZjUzYTYzOWFlY2RhZjU2MGFjYjQxMzc3NzUwMGU= # Enter your NextAuth secret here in base64 encoded format
  NEXT_PUBLIC_API_KEY: QUl6YVN5RGdjR1I0VzZqcWxqNU5JcXdYZ3Y2MUlHR09BcUVONmZv # Enter your API key here in base64 encoded format
  MONGODB_URI: <enter-your-mongodb-uri> # Enter your MongoDB URI here in base64 encoded format
