apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  namespace: gemini-namespace 
type: Opaque
data:
  GOOGLE_ID: MjMzMDk1Nzc0NzYzLXVsZmVtZGdzaTkycDFzdWl0N3A1bTZnajc3cGxrYW9nLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t # Enter your Google ID here in base64 encoded format
  GOOGLE_SECRET: R09DU1BYLXVya3NtZE9RdmstV2MwWWJrZ3VHSGJZNHVxWi0= # Enter your Google secret here in base64 encoded format
  NEXTAUTH_SECRET: BETTER_AUTH_SECRET=268b2e03520ed3e81c52e819550aa7a8f6ef22f2cd81225b6621ee3a5e663189 # Enter your NextAuth secret here in base64 encoded format
  NEXT_PUBLIC_API_KEY: QVEuQWI4Uk42STFYX0hWYkNwNDFpcHl6YVN2UTdzbFllVHBJNzFqb1ZGbkxCeG5kaTlrckE= # Enter your API key here in base64 encoded format
  MONGODB_URI: <enter-your-mongodb-uri> # Enter your MongoDB URI here in base64 encoded format
